---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: web
  namespace: flux-system
spec:
  image: ghghcr.io/iteam1337/gitops-kodlunch-web
  interval: 30s
  provider: generic
  secretRef:
    name: regcred
