---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 30s
  dependsOn:
  - name: git
  - name: infra-configs
  - name: infra-controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/nginx
  prune: true
  wait: true
  timeout: 2m0s
