apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-kodlunch
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  secretRef:
    name: git
  url: ssh://git@github.com:22/iteam1337/gitops-kodlunch.git
